### ISSUE TITLE
[P1] Fix document download/deletion test fixture errors (9 tests)

### ISSUE THREAD

**Issue by stack-driven** [bru-digital/qteria#257]
## Problem

Document download and deletion tests are failing with fixture-related errors after PR #254.

### Download Tests (3 failures)
```
FAILED test_download_success - AttributeError: 'tuple' object has no attribute 'id'
FAILED test_download_with_page_parameter - AttributeError: 'tuple' object has no attribute 'id'
FAILED test_download_blob_storage_failure - AttributeError: 'tuple' object has no attribute 'id'
```

### Deletion Tests (6 failures)
```
FAILED test_delete_document_not_in_assessment_success - NameError: name 'mock_db' is not defined
FAILED test_delete_document_in_pending_assessment_allowed - TypeError: 'Document' object is not subscriptable
FAILED test_delete_document_in_completed_assessment_conflict - TypeError: 'Document' object is not subscriptable
FAILED test_delete_document_in_processing_assessment_conflict - TypeError: 'Document' object is not subscriptable
FAILED test_delete_blob_failure_still_deletes_db - TypeError: 'Document' object is not subscriptable
```

### Download Tests: Fixture Returns Tuple Instead of Document Object
The download test fixtures are likely returning `(document, assessment)` tuples when tests expect just `document` object.

**Fix**: Update fixtures to return proper Document objects or update tests to destructure tuples.

### Deletion Tests: Multiple Issues
1. **NameError**: `mock_db` is not defined - test is referencing undefined variable
2. **TypeError**: Tests trying to subscript Document object like `document['id']` instead of `document.id`

## Investigation Needed

1. **Check document fixtures** (`tests/conftest.py` and `tests/test_documents_api.py`)
   - What does `document_fixture` return?
   - What does `assessment_with_document` fixture return?
   - Are fixtures properly typed?

2. **Check test expectations**
   - Are tests expecting wrong fixture return types?
   - Are tests using correct attribute access (`.id` vs `['id']`)?

3. **Check for undefined mocks**
   - Search for `mock_db` usage in deletion tests
   - Ensure all mocks are properly defined in fixtures

## Debugging Steps

```bash
# Debug download test
pytest tests/test_documents_api.py::TestDocumentDownload::test_download_success -vv --tb=long

# Debug deletion test  
pytest tests/test_documents_api.py::TestDocumentDeletion::test_delete_document_not_in_assessment_success -vv --tb=long

# Check fixture implementations
grep -n "def document" tests/conftest.py tests/test_documents_api.py
```

## Acceptance Criteria

- [ ] All 3 download tests pass
- [ ] All 6 deletion tests pass  
- [ ] Fixtures return consistent, properly-typed objects
- [ ] Tests use correct attribute access patterns
- [ ] No undefined variables (mock_db)

## Related

- PR #254: Database session isolation fix (exposed these issues)
- Issue #253: Test stabilization tracker
- Issue #248: Similar fixture data constraint issues (may be related)

## Priority

**P1 - HIGH**: Core document management functionality broken, but isolated to specific test classes.

**Comment by stack-driven** [comment]
## 🔍 Detailed Root Cause Analysis

After comprehensive error log analysis, I've identified **2 distinct fixture bugs** affecting 7 tests (originally reported as 9, but analysis shows 7).

---

## Bug 1: Fixture Returns Tuple Instead of Document Object

**Priority:** P1
**Affected Tests:** 3

### Error Pattern
```
AttributeError: 'tuple' object has no attribute 'id'
```

### Root Cause
The `test_document_in_org_a` fixture returns a **tuple** `(document, user)` instead of just the `Document` object.

**Evidence:**
```python
# Current fixture implementation (WRONG):
@pytest.fixture
def test_document_in_org_a(db_session, test_user_org_a_admin):
    doc = Document(...)
    db_session.add(doc)
    db_session.commit()
    return (doc, test_user_org_a_admin)  # ❌ Returns tuple

# Test usage (expects Document):
def test_download_success(client, test_document_in_org_a):
    doc_id = test_document_in_org_a.id  # ❌ Tries to access .id on tuple
    # AttributeError: 'tuple' object has no attribute 'id'
```

### Affected Tests (3)
```
test_download_success (line 2109 in tests/test_documents_api.py)
test_download_with_page_parameter (line 2143)
test_download_blob_storage_failure (line 2264)
```

### Solution

**Option A: Return Only Document Object (RECOMMENDED)**
```python
@pytest.fixture
def test_document_in_org_a(db_session, test_user_org_a_admin):
    doc = Document(
        organization_id=TEST_ORG_A_ID,
        uploaded_by=test_user_org_a_admin.id,
        file_name="test_document.pdf",
        file_size=1024,
        mime_type="application/pdf",
        storage_key="https://blob.vercel-storage.com/test.pdf",
    )
    db_session.add(doc)
    db_session.commit()
    return doc  # ✅ Return only document (matches fixture name)
```

**Option B: Update Tests to Unpack Tuple**
```python
def test_download_success(client, test_document_in_org_a):
    doc, user = test_document_in_org_a  # Unpack tuple
    doc_id = doc.id
    # ... rest of test
```

**Recommendation:** **Option A** - Fixture names should match return types. `test_document_in_org_a` (singular) implies single object, not tuple.

---

## Bug 2: Tests Try to Subscript Non-Subscriptable Document Object

**Priority:** P1
**Affected Tests:** 4

### Error Pattern
```
TypeError: 'Document' object is not subscriptable
```

### Root Cause
Tests try to **index a Document object like a list** (e.g., `documents[0]`) when the fixture returns a single Document, not a list.

**Evidence:**
```python
# Fixture returns single Document:
@pytest.fixture
def test_document_with_assessment(db_session):
    doc = Document(...)
    assessment = Assessment(...)
    # ...
    return doc  # Single object, not list

# Test tries to index it:
def test_delete_document_in_pending_assessment_allowed(client, test_document_with_assessment):
    doc_id = test_document_with_assessment[0].id  # ❌ Can't subscript Document
    # TypeError: 'Document' object is not subscriptable
```

### Affected Tests (4)
```
test_delete_document_in_pending_assessment_allowed (line 2375)
test_delete_document_in_completed_assessment_conflict (line 2422)
test_delete_document_in_processing_assessment_conflict (line 2485)
test_delete_blob_failure_still_deletes_db (line 2606)
```

### Solution

**Option A: Update Tests to Not Use Subscript (RECOMMENDED)**
```python
def test_delete_document_in_pending_assessment_allowed(client, test_document_with_assessment):
    doc_id = test_document_with_assessment.id  # ✅ Direct access (no subscript)
    response = client.delete(f"/v1/documents/{doc_id}")
    assert response.status_code == 200
```

**Option B: Make Fixture Return List**
```python
@pytest.fixture
def test_documents_with_assessment(db_session):  # Plural name
    docs = [Document(...), Document(...)]
    db_session.add_all(docs)
    return docs  # ✅ Returns list (matches plural name)
```

**Recommendation:** **Option A** - Most tests only need one document. Simpler to fix tests than change fixture contract.

---

## Summary

| Bug Type | Tests | Fix Effort | Recommendation |
|----------|-------|------------|----------------|
| Tuple instead of object | 3 | 5 min | Return Document only |
| Subscript error | 4 | 10 min | Remove subscript from tests |
| **Total** | **7** | **15 min** | **Option A for both** |

---

## Fixture Naming Convention (Recommendation)

To prevent this in future:

1. **Singular name = single object**
   - `test_document_in_org_a` → returns `Document`
   - `test_user_org_a_admin` → returns `User`

2. **Plural name = list of objects**
   - `test_documents_in_org_a` → returns `List[Document]`
   - `test_users_org_a` → returns `List[User]`

3. **Tuple return = explicit name**
   - `test_document_with_user` → returns `Tuple[Document, User]`
   - Document in CLAUDE.md testing section

---

## Acceptance Criteria (Updated)

**Bug 1: Tuple Return**
- [ ] `test_document_in_org_a` fixture returns single Document object
- [ ] `test_download_success` passes
- [ ] `test_download_with_page_parameter` passes
- [ ] `test_download_blob_storage_failure` passes

**Bug 2: Subscript Error**
- [ ] `test_delete_document_in_pending_assessment_allowed` passes
- [ ] `test_delete_document_in_completed_assessment_conflict` passes
- [ ] `test_delete_document_in_processing_assessment_conflict` passes
- [ ] `test_delete_blob_failure_still_deletes_db` passes

**Documentation:**
- [ ] Add fixture naming convention to `apps/api/docs/testing.md`
- [ ] Document in CLAUDE.md (#250)

---

## Related

- Analysis: `test-failure-analysis-summary.md` Categories 3 & 4
- Part of: #253 (tracker)
- Documentation: #250 (testing patterns)

## Priority

**P1 - HIGH**: Affects 7 tests, but simple fixes (15 minutes total). Can be done after P0 issues (#264, #256, #265).
